"""empty message

Revision ID: 30e52b9d6851
Revises: 53a218c045ef
Create Date: 2025-08-31 20:40:32.928377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30e52b9d6851'
down_revision = '53a218c045ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discipline_reviews', schema=None) as batch_op:
        batch_op.alter_column('difficulty',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    with op.batch_alter_table('teacher_reviews', schema=None) as batch_op:
        batch_op.alter_column('difficulty',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_reviews', schema=None) as batch_op:
        batch_op.alter_column('difficulty',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('discipline_reviews', schema=None) as batch_op:
        batch_op.alter_column('difficulty',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
